#
# This source file is part of the Stanford Biodesign Digital Health Group Swift Template Package open source project
#
# SPDX-FileCopyrightText: 2025 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: Build-and-Test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  package_tests:
    name: Build and Test Swift Package ${{ matrix.platform.name }} (${{ matrix.config }})
    uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    strategy:
      matrix:
        config: [Debug]
        platform:
          - name: macOS
            destination: 'platform=macOS,arch=arm64'
      fail-fast: false
    with:
      runsonlabels: '["macOS", "self-hosted"]'
      scheme: MHCStudyDefinition-Package
      destination: ${{ matrix.platform.destination }}
      buildConfig: ${{ matrix.config }}
      resultBundle: ${{ format('MHCStudyDefinition-Package-{0}-{1}.xcresult', matrix.platform.name, matrix.config) }}
      artifactname: ${{ format('MHCStudyDefinition-Package-{0}-{1}.xcresult', matrix.platform.name, matrix.config) }}
  uploadcoveragereport:
    name: Upload Coverage Report
    needs: [package_tests]
    uses: StanfordBDHG/.github/.github/workflows/create-and-upload-coverage-report.yml@v2
    with:
      coveragereports: MHCStudyDefinition-Package-*.xcresult
    secrets:
      token: ${{ secrets.CODECOV_TOKEN }}