#
# This source file is part of the Stanford Biodesign Digital Health Group Swift Template Package open source project
#
# SPDX-FileCopyrightText: 2025 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: Build-and-Test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  package_tests:
    name: Verify Study Bundle Integrity
    uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@lukas/use_xcbeautify
    with:
      customcommand: 'swift test'
