name: Publish Study Definition

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  vars:
    name: Inject Environment Variables
    runs-on: ubuntu-latest
    environment: staging
    outputs:
      FIREBASE_PROJECT_ID: ${{ vars.FIREBASE_PROJECT_ID }}
    steps:
      - run: |
          echo "Injecting Environment Variables: ${{ vars.FIREBASE_PROJECT_ID }}"

  publish:
    name: Build and Upload Study Bundle
    needs: vars
    runs-on: macos-latest
    environment: staging
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Build study bundle
      run: |
        swift run MHCStudyDefinitionExporterCLI export .

    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Decode and authenticate to Google Cloud
      run: |
        if [ -z "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_BASE64 }}" ]; then
          echo "ERROR: GOOGLE_APPLICATION_CREDENTIALS_BASE64 secret is not set"
          exit 1
        fi
        if [ -z "${{ needs.vars.outputs.FIREBASE_PROJECT_ID }}" ]; then
          echo "ERROR: FIREBASE_PROJECT_ID variable is not set"
          exit 1
        fi

        echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_BASE64 }}" | base64 -d > /tmp/gcp-key.json

        if [ ! -s /tmp/gcp-key.json ]; then
          echo "ERROR: Failed to decode credentials or file is empty"
          exit 1
        fi

        gcloud auth activate-service-account --key-file=/tmp/gcp-key.json
        gcloud config set project ${{ needs.vars.outputs.FIREBASE_PROJECT_ID }}

    - name: Upload study bundle to Firebase Storage
      run: |
        gsutil cp mhcStudyBundle.spezistudybundle.aar gs://${{ needs.vars.outputs.FIREBASE_PROJECT_ID }}.appspot.com/public/

        gsutil acl ch -u AllUsers:R gs://${{ needs.vars.outputs.FIREBASE_PROJECT_ID }}.appspot.com/public/mhcStudyBundle.spezistudybundle.aar

    - name: Verify upload
      run: |
        # List the files in the public directory to confirm upload
        gsutil ls gs://${{ needs.vars.outputs.FIREBASE_PROJECT_ID }}.appspot.com/public/